import Foundation
import Metal

public enum NumiVivoShaderError:Error,Sendable,CustomStringConvertible{case sourceResourceMissing;case functionMissing(String);case compilationFailed(String);case pipelineFailed(String,String);public var description:String{switch self{case .sourceResourceMissing:return"The selected NumiVivo shader source resource is missing.";case .functionMissing(let n):return"Metal function '\(n)' is missing from its selected module.";case .compilationFailed(let m):return"NumiVivo Metal compilation failed: \(m)";case .pipelineFailed(let n,let m):return"NumiVivo pipeline '\(n)' could not be created: \(m)"}}}
public enum NumiVivoKernel:String,CaseIterable,Sendable{
    case clearStatus="nvivo_clear_status",prepareTransaction="nvivo_prepare_transaction",applyCouplingUpdates="nvivo_apply_coupling_updates",f1HeunPredict="nvivo_f1_heun_predict",f1HeunCorrect="nvivo_f1_heun_correct",f2SampleReactions="nvivo_f2_sample_reactions",f2ApplyReactions="nvivo_f2_apply_reactions",f3Transport="nvivo_f3_transport",executeRules="nvivo_execute_rules",evaluateMonitors="nvivo_evaluate_monitors",validateShadow="nvivo_validate_shadow",publish="nvivo_publish"
    case physiologyClearStatus="nvivo_phys_clear_status",physiologyPrepareTransaction="nvivo_phys_prepare_transaction",physiologyApplyTransforms="nvivo_phys_apply_transforms",physiologyHeunPredict="nvivo_phys_heun_predict",physiologyHeunCorrect="nvivo_phys_heun_correct",physiologyValidateCandidate="nvivo_phys_validate_candidate",physiologyPublish="nvivo_phys_publish"
    case mdClearForce="nvivo_md_clear_force",mdClearStatus="nvivo_md_clear_status",mdUpdateVirtualPosition="nvivo_md_update_virtual_position",mdUpdateVirtualVelocity="nvivo_md_update_virtual_velocity",mdRedistributeVirtualForce="nvivo_md_redistribute_virtual_force",mdBonded="nvivo_md_bonded",mdBuildNeighborList="nvivo_md_build_neighbor_list",mdValidateNeighborDisplacement="nvivo_md_validate_neighbor_displacement",mdNonbondedNeighbor="nvivo_md_nonbonded_neighbor",mdNonbondedDirect="nvivo_md_nonbonded_direct",mdHalfKick="nvivo_md_half_kick",mdDrift="nvivo_md_drift",mdLangevin="nvivo_md_langevin",mdConstraintPosition="nvivo_md_constraint_position",mdConstraintVelocity="nvivo_md_constraint_velocity",mdValidateConstraints="nvivo_md_validate_constraints",mdKinetic="nvivo_md_kinetic",mdValidate="nvivo_md_validate"
    fileprivate var sourceModule:String{switch self{case .physiologyClearStatus,.physiologyPrepareTransaction,.physiologyApplyTransforms,.physiologyHeunPredict,.physiologyHeunCorrect,.physiologyValidateCandidate,.physiologyPublish:return"NumiVivoPhysiologyKernels";case .mdClearForce,.mdClearStatus,.mdUpdateVirtualPosition,.mdUpdateVirtualVelocity,.mdRedistributeVirtualForce,.mdBonded,.mdBuildNeighborList,.mdValidateNeighborDisplacement,.mdNonbondedNeighbor,.mdNonbondedDirect,.mdHalfKick,.mdDrift,.mdLangevin,.mdConstraintPosition,.mdConstraintVelocity,.mdValidateConstraints,.mdKinetic,.mdValidate:return"NumiVivoMDKernels";default:return"NumiVivoProgramPackRuntime"}}
}
public struct NumiVivoPipeline:@unchecked Sendable{public let state:MTLComputePipelineState;public let executionWidth:Int;public let maximumThreadsPerThreadgroup:Int;public init(state:MTLComputePipelineState){self.state=state;executionWidth=state.threadExecutionWidth;maximumThreadsPerThreadgroup=state.maxTotalThreadsPerThreadgroup}public func threadgroupSize(for elementCount:Int,preferred:Int?=nil)->MTLSize{let w=max(executionWidth,1),r=max(w,preferred ?? w*4),c=min(r,maximumThreadsPerThreadgroup),a=max(1,c>=w ? (c/w)*w:c);return .init(width:a,height:1,depth:1)}public func gridSize(for elementCount:Int)->MTLSize{.init(width:max(elementCount,1),height:1,depth:1)}}
private final class NumiVivoRuntimeLibraryCache:@unchecked Sendable{static let shared=NumiVivoRuntimeLibraryCache();private let lock=NSLock();private var libraries:[String:MTLLibrary]=[:];func library(device:MTLDevice,module:String)throws->MTLLibrary{lock.lock();defer{lock.unlock()};let key="\(device.registryID)/\(module)/v1";if let v=libraries[key]{return v};let url=Bundle.module.url(forResource:module,withExtension:"metal") ?? Bundle.module.url(forResource:module,withExtension:"metal",subdirectory:"Resources");guard let url else{throw NumiVivoShaderError.sourceResourceMissing};do{let s=try String(contentsOf:url,encoding:.utf8),o=MTLCompileOptions();o.fastMathEnabled=false;let l=try device.makeLibrary(source:s,options:o);libraries[key]=l;return l}catch{throw NumiVivoShaderError.compilationFailed(String(describing:error))}}}
public actor NumiVivoPipelineCatalog{private let device:MTLDevice;private var cache:[NumiVivoKernel:NumiVivoPipeline]=[:];public init(device:MTLDevice)throws{self.device=device}public func pipeline(_ k:NumiVivoKernel)throws->NumiVivoPipeline{if let v=cache[k]{return v};let l=try NumiVivoRuntimeLibraryCache.shared.library(device:device,module:k.sourceModule);guard let f=l.makeFunction(name:k.rawValue)else{throw NumiVivoShaderError.functionMissing(k.rawValue)};do{let d=MTLComputePipelineDescriptor();d.label="NumiVivo.\(k.rawValue)";d.computeFunction=f;d.threadGroupSizeIsMultipleOfThreadExecutionWidth=false;let s=try device.makeComputePipelineState(descriptor:d,options:[],reflection:nil),v=NumiVivoPipeline(state:s);cache[k]=v;return v}catch{throw NumiVivoShaderError.pipelineFailed(k.rawValue,String(describing:error))}}public func preloadAll()throws{for k in NumiVivoKernel.allCases{_=try pipeline(k)}}}
