import Foundation

public struct VivoReactionHessianConfiguration: Codable, Sendable, Equatable {
    public var displacementBohr:Double; public var zeroModeTolerance:Double; public var symmetryTolerance:Double
    public init(displacementBohr:Double=1e-3,zeroModeTolerance:Double=1e-6,symmetryTolerance:Double=1e-7){self.displacementBohr=displacementBohr;self.zeroModeTolerance=zeroModeTolerance;self.symmetryTolerance=symmetryTolerance}
    public func validate()throws{guard displacementBohr.isFinite,(1e-5...1e-1).contains(displacementBohr),zeroModeTolerance.isFinite,zeroModeTolerance>0,symmetryTolerance.isFinite,symmetryTolerance>0 else{throw VivoChemistryError.invalid("reaction Hessian configuration")}}
}
public struct VivoStationaryPointCharacterization: Codable, Sendable, Equatable {
    public let positionsBohr:[SIMD3<Double>],massesDa:[Double],energyHartree:Double,gradientRMSHartreePerBohr:Double,maximumGradientHartreePerBohr:Double
    public let hessianHartreePerBohrSquared:VivoQMMatrix,projectedMassWeightedEigenvalues:[Double]
    public let rigidModeCount:Int,vibrationalModeCount:Int,imaginaryModeCount:Int,hessianDisplacementBohr:Double,status:String
    public func fingerprint()throws->VivoFingerprint{try VivoCanonicalJSON.fingerprint(VivoCanonicalJSON.encode(self))}
}
enum VivoReactionPathMath {
    static func flat(_ v:[SIMD3<Double>])->[Double]{v.flatMap{[$0.x,$0.y,$0.z]}}
    static func vectors(_ f:[Double])->[SIMD3<Double>]{stride(from:0,to:f.count,by:3).map{.init(f[$0],f[$0+1],f[$0+2])}}
    static func metrics(_ g:[SIMD3<Double>])->(Double,Double){let f=flat(g);return(sqrt(f.reduce(0){$0+$1*$1}/Double(f.count)),f.map(abs).max() ?? 0)}
    static func orthonormalize(_ candidates:[[Double]],tolerance:Double=1e-10)->[[Double]]{var basis:[[Double]]=[];for candidate in candidates{var v=candidate;for q in basis{let a=zip(v,q).reduce(0){$0+$1.0*$1.1};for i in v.indices{v[i]-=a*q[i]}};let n=sqrt(v.reduce(0){$0+$1*$1});if n>tolerance{basis.append(v.map{$0/n})}};return basis}
    static func rigid(positions:[SIMD3<Double>],masses:[Double])throws->[[Double]]{guard positions.count==masses.count,!positions.isEmpty,positions.allSatisfy(vivoQMFinite),masses.allSatisfy({$0.isFinite&&$0>0})else{throw VivoChemistryError.invalid("stationary-point positions/masses")};let total=masses.reduce(0,+);var center=SIMD3<Double>.zero;for i in positions.indices{center+=masses[i]*positions[i]};center/=total;var c:[[Double]]=[];for axis in 0..<3{var v=[Double](repeating:0,count:3*positions.count);for i in positions.indices{v[3*i+axis]=sqrt(masses[i])};c.append(v)};for axis in [SIMD3<Double>(1,0,0),.init(0,1,0),.init(0,0,1)]{var v=[Double](repeating:0,count:3*positions.count);for i in positions.indices{let r=positions[i]-center,x=SIMD3<Double>(axis.y*r.z-axis.z*r.y,axis.z*r.x-axis.x*r.z,axis.x*r.y-axis.y*r.x)*sqrt(masses[i]);v[3*i]=x.x;v[3*i+1]=x.y;v[3*i+2]=x.z};c.append(v)};return orthonormalize(c)}
    static func projector(_ n:Int,_ rigid:[[Double]])throws->VivoQMMatrix{var p=try VivoQMMatrix.identity(n);for q in rigid{for i in 0..<n{for j in 0..<n{p[i,j]-=q[i]*q[j]}}};return p}
    static func massWeighted(_ h:VivoQMMatrix,_ masses:[Double])throws->VivoQMMatrix{let n=3*masses.count;guard h.rows==n,h.columns==n else{throw VivoChemistryError.invalid("Hessian/mass dimensions")};var r=h;for i in 0..<n{for j in 0..<n{r[i,j]/=sqrt(masses[i/3]*masses[j/3])}};return r}
}
public enum VivoReactionHessian {
    public static func finiteDifference(positionsBohr:[SIMD3<Double>],configuration cfg:VivoReactionHessianConfiguration = .init(),maximumEvaluations:Int=100_000,evaluate:([SIMD3<Double>])throws->VivoGeometryEvaluation)throws->(center:VivoGeometryEvaluation,hessian:VivoQMMatrix,evaluations:Int){try cfg.validate();let n=3*positionsBohr.count;guard !positionsBohr.isEmpty,positionsBohr.allSatisfy(vivoQMFinite),n<=30_000,maximumEvaluations>=2*n+1 else{throw VivoChemistryError.resourceLimit("finite-difference Hessian budget")};let center=try evaluate(positionsBohr);guard center.energyHartree.isFinite,center.gradientHartreePerBohr.count==positionsBohr.count,center.gradientHartreePerBohr.allSatisfy(vivoQMFinite)else{throw VivoChemistryError.invalid("central Hessian evaluation")};var h=VivoQMMatrix(n,n);for c in 0..<n{var plus=positionsBohr,minus=positionsBohr;plus[c/3][c%3]+=cfg.displacementBohr;minus[c/3][c%3]-=cfg.displacementBohr;let gp=try evaluate(plus),gm=try evaluate(minus);guard gp.gradientHartreePerBohr.count==positionsBohr.count,gm.gradientHartreePerBohr.count==positionsBohr.count else{throw VivoChemistryError.invalid("displaced Hessian gradient")};let a=VivoReactionPathMath.flat(gp.gradientHartreePerBohr),b=VivoReactionPathMath.flat(gm.gradientHartreePerBohr);for r in 0..<n{h[r,c]=(a[r]-b[r])/(2*cfg.displacementBohr)}};let asym=try h.adding(h.transposed,scale:-1).frobeniusNorm;guard asym<=cfg.symmetryTolerance*max(1,h.frobeniusNorm)else{throw VivoChemistryError.convergence("finite-difference Hessian asymmetry")};h=try h.adding(h.transposed).scaled(0.5);return(center,h,2*n+1)}
    public static func characterize(positionsBohr:[SIMD3<Double>],massesDa:[Double],center:VivoGeometryEvaluation,hessian:VivoQMMatrix,configuration cfg:VivoReactionHessianConfiguration = .init())throws->VivoStationaryPointCharacterization{try cfg.validate();guard massesDa.count==positionsBohr.count,center.gradientHartreePerBohr.count==positionsBohr.count else{throw VivoChemistryError.invalid("stationary-point dimensions")};let rigid=try VivoReactionPathMath.rigid(positions:positionsBohr,masses:massesDa),mw=try VivoReactionPathMath.massWeighted(hessian,massesDa),p=try VivoReactionPathMath.projector(hessian.rows,rigid),projected=try p.multiplied(by:mw).multiplied(by:p),eig=try VivoQMDenseAlgebra.symmetricEigen(projected,tolerance:min(1e-12,cfg.zeroModeTolerance*1e-3),maximumSweeps:256),scale=max(1,eig.values.map(abs).max() ?? 1),active=eig.values.filter{abs($0)>cfg.zeroModeTolerance*scale},m=VivoReactionPathMath.metrics(center.gradientHartreePerBohr);return .init(positionsBohr:positionsBohr,massesDa:massesDa,energyHartree:center.energyHartree,gradientRMSHartreePerBohr:m.0,maximumGradientHartreePerBohr:m.1,hessianHartreePerBohrSquared:hessian,projectedMassWeightedEigenvalues:active,rigidModeCount:rigid.count,vibrationalModeCount:active.count,imaginaryModeCount:active.filter{$0<0}.count,hessianDisplacementBohr:cfg.displacementBohr,status:"mass-weighted Hessian with rigid-mode projection")}
}
