#include <metal_stdlib>
using namespace metal;
namespace nvivo_md {
struct Command{uint particleCount,typeCount,electrostatics,periodic;uint stepLow,stepHigh,seedLow,seedHigh;float dtPS,cutoffNM,coulombPrefactor,reactionFieldK;float reactionFieldC,minimumDistanceNM,constraintTolerance,langevinA;float targetTemperatureK,boltzmannKJPerMolK;uint neighborCapacity;float neighborRadiusNM;float4 cellA,cellB,cellC,reciprocalA,reciprocalB,reciprocalC;};
struct Status{atomic_uint flags,firstParticle,violationCount,reserved;};
struct Bond{uint2 atoms;float2 parameters;};struct Angle{uint4 atoms;float2 parameters;};struct Torsion{uint4 atoms;float4 parameters;};struct Constraint{uint2 atoms;float distanceNM;uint pad;};struct Incidence{uint termIndex,localIndex;};struct PairException{uint2 atoms;float2 scales;float2 overrideC12C6;uint flags;};
constant uint statusNonFinite=1u,statusOverlap=2u,statusInvalidGeometry=4u,statusConstraint=8u,statusNeighborOverflow=16u,statusNeighborStale=32u;
inline void fail(device Status&s,uint flag,uint p){atomic_fetch_or_explicit(&s.flags,flag,memory_order_relaxed);atomic_fetch_min_explicit(&s.firstParticle,p,memory_order_relaxed);atomic_fetch_add_explicit(&s.violationCount,1u,memory_order_relaxed);}
inline float3 minimumImage(float3 d,constant Command&c){if(c.periodic==0)return d;float3 f=float3(dot(c.reciprocalA.xyz,d),dot(c.reciprocalB.xyz,d),dot(c.reciprocalC.xyz,d));f-=rint(f);return c.cellA.xyz*f.x+c.cellB.xyz*f.y+c.cellC.xyz*f.z;}
inline float3 wrapPosition(float3 p,constant Command&c){if(c.periodic==0)return p;float3 f=float3(dot(c.reciprocalA.xyz,p),dot(c.reciprocalB.xyz,p),dot(c.reciprocalC.xyz,p));f-=floor(f);return c.cellA.xyz*f.x+c.cellB.xyz*f.y+c.cellC.xyz*f.z;}
inline int findException(uint owner,uint partner,device const uint*o,device const uint*p,device const uint*i){uint lo=o[owner],hi=o[owner+1];while(lo<hi){uint m=lo+(hi-lo)/2,v=p[m];if(v<partner)lo=m+1;else hi=m;}return lo<o[owner+1]&&p[lo]==partner?int(i[lo]):-1;}
inline float4 pairContribution(uint owner,uint j,device const float4*p,device const float4*dyn,device const uint*types,device const float2*pair,device const PairException*exs,device const uint*eo,device const uint*ep,device const uint*ei,constant Command&c,device Status&s){float3 d=minimumImage(p[owner].xyz-p[j].xyz,c);float r2=dot(d,d);if(r2>=c.cutoffNM*c.cutoffNM)return 0;if(!(r2>c.minimumDistanceNM*c.minimumDistanceNM)||!isfinite(r2)){fail(s,statusOverlap,owner);return 0;}float ir=rsqrt(r2),ir2=ir*ir,cs=1,ls=1;float2 coeff=pair[types[owner]*c.typeCount+types[j]];int ex=findException(owner,j,eo,ep,ei);if(ex>=0){PairException v=exs[ex];cs=v.scales.x;ls=v.scales.y;if((v.flags&1u)!=0)coeff=v.overrideC12C6;}float ir6=ir2*ir2*ir2,ir12=ir6*ir6,lj=ls*(coeff.x*ir12-coeff.y*ir6),lf=ls*(12.0f*coeff.x*ir12-6.0f*coeff.y*ir6)*ir2;float qq=dyn[owner].z*dyn[j].z,ce=0,cf=0;if(cs!=0&&qq!=0){if(c.electrostatics==0){ce=c.coulombPrefactor*qq*ir;cf=c.coulombPrefactor*qq*ir*ir2;}else{ce=c.coulombPrefactor*qq*(ir+c.reactionFieldK*r2-c.reactionFieldC);cf=c.coulombPrefactor*qq*(ir*ir2-2.0f*c.reactionFieldK);}ce*=cs;cf*=cs;}return float4((lf+cf)*d,0.5f*(lj+ce));}
inline float4 bondContribution(uint local,Bond t,device const float4*p,constant Command&c,device Status&s,uint owner){float3 d=minimumImage(p[t.atoms.x].xyz-p[t.atoms.y].xyz,c);float r2=dot(d,d);if(!(r2>c.minimumDistanceNM*c.minimumDistanceNM)||!isfinite(r2)){fail(s,statusInvalidGeometry,owner);return 0;}float r=sqrt(r2),dr=r-t.parameters.x,e=.5f*t.parameters.y*dr*dr;float3 fa=-t.parameters.y*dr*d/r;return float4(local==0?fa:-fa,.5f*e);}
inline float4 angleContribution(uint local,Angle t,device const float4*p,constant Command&c,device Status&s,uint owner){float3 u=minimumImage(p[t.atoms.x].xyz-p[t.atoms.y].xyz,c),v=minimumImage(p[t.atoms.z].xyz-p[t.atoms.y].xyz,c);float u2=dot(u,u),v2=dot(v,v);if(!(u2>1e-16f&&v2>1e-16f)){fail(s,statusInvalidGeometry,owner);return 0;}float ru=sqrt(u2),rv=sqrt(v2),co=clamp(dot(u,v)/(ru*rv),-1.f,1.f),th=acos(co),si=sqrt(max(1.f-co*co,1e-12f)),dE=t.parameters.y*(th-t.parameters.x);float3 ga=(co*u/u2-v/(ru*rv))/si,gc=(co*v/v2-u/(ru*rv))/si,fa=-dE*ga,fc=-dE*gc,fb=-(fa+fc);float d=th-t.parameters.x;return float4(local==0?fa:(local==1?fb:fc),(.5f*t.parameters.y*d*d)/3.f);}
inline float4 torsionContribution(uint local,Torsion t,device const float4*p,constant Command&c,device Status&s,uint owner){float3 d0=minimumImage(p[t.atoms.x].xyz-p[t.atoms.y].xyz,c),d1=minimumImage(p[t.atoms.z].xyz-p[t.atoms.y].xyz,c),d2=minimumImage(p[t.atoms.z].xyz-p[t.atoms.w].xyz,c),c1=cross(d0,d1),c2=cross(d1,d2);float c1q=dot(c1,c1),c2q=dot(c2,c2),d1q=dot(d1,d1);if(!(c1q>1e-16f&&c2q>1e-16f&&d1q>1e-16f)){fail(s,statusInvalidGeometry,owner);return 0;}float l=sqrt(d1q),phi=atan2(dot(d1,cross(c1,c2))/l,dot(c1,c2)),n=t.parameters.x,phase=t.parameters.y,k=t.parameters.z,e=k*(1.f+cos(n*phi-phase)),de=-k*n*sin(n*phi-phase);float3 f0=c1*(de*l/c1q),f3=c2*(-de*l/c2q);float q0=dot(d0,d1)/d1q,q2=dot(d2,d1)/d1q;float3 f1=f0*(q0-1.f)-f3*q2,f2=-f0*q0+f3*(q2-1.f);return float4(local==0?f0:(local==1?f1:(local==2?f2:f3)),e*.25f);}
inline uint4 philox(uint4 x,uint2 k){for(uint r=0;r<10;++r){uint h0=mulhi(0xD2511F53u,x.x),h1=mulhi(0xCD9E8D57u,x.z);x=uint4(h1^x.y^k.x,0xCD9E8D57u*x.z,h0^x.w^k.y,0xD2511F53u*x.x);k+=uint2(0x9E3779B9u,0xBB67AE85u);}return x;}inline float u01(uint x){return(float(x>>9)+.5f)*0x1p-23f;}inline float4 normal4(uint p,constant Command&c){uint4 b=philox(uint4(p,c.stepLow,c.stepHigh,0x4d44544du),uint2(c.seedLow,c.seedHigh));float u0=u01(b.x),u1=u01(b.y),u2=u01(b.z),u3=u01(b.w),r0=sqrt(-2.f*log(u0)),a0=6.28318530718f*u1,r1=sqrt(-2.f*log(u2)),a1=6.28318530718f*u3;return float4(r0*cos(a0),r0*sin(a0),r1*cos(a1),r1*sin(a1));}

[[host_name("nvivo_md_clear_force")]] kernel void nvivo_md_clear_force(device float4*fe[[buffer(0)]],constant Command&c[[buffer(1)]],uint g[[thread_position_in_grid]]){if(g<c.particleCount)fe[g]=0;}
[[host_name("nvivo_md_clear_status")]] kernel void nvivo_md_clear_status(device Status&s[[buffer(0)]],uint g[[thread_position_in_grid]]){if(g==0){atomic_store_explicit(&s.flags,0,memory_order_relaxed);atomic_store_explicit(&s.firstParticle,0xffffffffu,memory_order_relaxed);atomic_store_explicit(&s.violationCount,0,memory_order_relaxed);atomic_store_explicit(&s.reserved,0,memory_order_relaxed);}}
[[host_name("nvivo_md_bonded")]] kernel void nvivo_md_bonded(device const float4*p[[buffer(0)]],device float4*fe[[buffer(1)]],device const Bond*b[[buffer(2)]],device const uint*bo[[buffer(3)]],device const Incidence*bi[[buffer(4)]],device const Angle*a[[buffer(5)]],device const uint*ao[[buffer(6)]],device const Incidence*ai[[buffer(7)]],device const Torsion*t[[buffer(8)]],device const uint*to[[buffer(9)]],device const Incidence*ti[[buffer(10)]],device Status&s[[buffer(11)]],constant Command&c[[buffer(12)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount)return;float4 sum=0;for(uint i=bo[g];i<bo[g+1];++i){Incidence e=bi[i];sum+=bondContribution(e.localIndex,b[e.termIndex],p,c,s,g);}for(uint i=ao[g];i<ao[g+1];++i){Incidence e=ai[i];sum+=angleContribution(e.localIndex,a[e.termIndex],p,c,s,g);}for(uint i=to[g];i<to[g+1];++i){Incidence e=ti[i];sum+=torsionContribution(e.localIndex,t[e.termIndex],p,c,s,g);}if(!all(isfinite(sum))){fail(s,statusNonFinite,g);return;}fe[g]+=sum;}

[[host_name("nvivo_md_build_neighbor_list")]] kernel void nvivo_md_build_neighbor_list(device const float4*p[[buffer(0)]],device uint*counts[[buffer(1)]],device uint*indices[[buffer(2)]],device float4*reference[[buffer(3)]],device Status&s[[buffer(4)]],constant Command&c[[buffer(5)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount)return;uint n=0;float r2max=c.neighborRadiusNM*c.neighborRadiusNM;for(uint j=0;j<c.particleCount;++j){if(j==g)continue;float3 d=minimumImage(p[g].xyz-p[j].xyz,c);if(dot(d,d)<r2max){if(n<c.neighborCapacity)indices[ulong(g)*c.neighborCapacity+n]=j;++n;}}if(n>c.neighborCapacity)fail(s,statusNeighborOverflow,g);counts[g]=min(n,c.neighborCapacity);reference[g]=p[g];}
[[host_name("nvivo_md_validate_neighbor_displacement")]] kernel void nvivo_md_validate_neighbor_displacement(device const float4*p[[buffer(0)]],device const float4*reference[[buffer(1)]],device Status&s[[buffer(2)]],constant Command&c[[buffer(3)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount)return;float halfSkin=.5f*(c.neighborRadiusNM-c.cutoffNM);float3 d=minimumImage(p[g].xyz-reference[g].xyz,c);if(!(halfSkin>0)||dot(d,d)>halfSkin*halfSkin)fail(s,statusNeighborStale,g);}
[[host_name("nvivo_md_nonbonded_neighbor")]] kernel void nvivo_md_nonbonded_neighbor(device const float4*p[[buffer(0)]],device float4*fe[[buffer(1)]],device const float4*dyn[[buffer(2)]],device const uint*types[[buffer(3)]],device const float2*pair[[buffer(4)]],device const PairException*exs[[buffer(5)]],device const uint*eo[[buffer(6)]],device const uint*ep[[buffer(7)]],device const uint*ei[[buffer(8)]],device const uint*counts[[buffer(9)]],device const uint*neighbors[[buffer(10)]],device Status&s[[buffer(11)]],constant Command&c[[buffer(12)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount)return;uint flags=atomic_load_explicit(&s.flags,memory_order_relaxed);if((flags&(statusNeighborOverflow|statusNeighborStale))!=0)return;float4 sum=0;uint n=counts[g];for(uint k=0;k<n;++k)sum+=pairContribution(g,neighbors[ulong(g)*c.neighborCapacity+k],p,dyn,types,pair,exs,eo,ep,ei,c,s);float4 v=fe[g]+sum;if(!all(isfinite(v))){fail(s,statusNonFinite,g);return;}fe[g]=v;}
[[host_name("nvivo_md_nonbonded_direct")]] kernel void nvivo_md_nonbonded_direct(device const float4*p[[buffer(0)]],device float4*fe[[buffer(1)]],device const float4*dyn[[buffer(2)]],device const uint*types[[buffer(3)]],device const float2*pair[[buffer(4)]],device const PairException*exs[[buffer(5)]],device const uint*eo[[buffer(6)]],device const uint*ep[[buffer(7)]],device const uint*ei[[buffer(8)]],device Status&s[[buffer(9)]],constant Command&c[[buffer(10)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount)return;float4 sum=0;for(uint j=0;j<c.particleCount;++j)if(j!=g)sum+=pairContribution(g,j,p,dyn,types,pair,exs,eo,ep,ei,c,s);float4 v=fe[g]+sum;if(!all(isfinite(v))){fail(s,statusNonFinite,g);return;}fe[g]=v;}

[[host_name("nvivo_md_half_kick")]] kernel void nvivo_md_half_kick(device float4*v[[buffer(0)]],device const float4*fe[[buffer(1)]],device const float4*dyn[[buffer(2)]],constant Command&c[[buffer(3)]],uint g[[thread_position_in_grid]]){if(g<c.particleCount&&dyn[g].y!=0)v[g].xyz+=.5f*c.dtPS*dyn[g].y*fe[g].xyz;}
[[host_name("nvivo_md_drift")]] kernel void nvivo_md_drift(device float4*p[[buffer(0)]],device const float4*v[[buffer(1)]],device const float4*dyn[[buffer(2)]],constant Command&c[[buffer(3)]],uint g[[thread_position_in_grid]]){if(g<c.particleCount&&dyn[g].y!=0)p[g].xyz=wrapPosition(p[g].xyz+c.dtPS*v[g].xyz,c);}
[[host_name("nvivo_md_langevin")]] kernel void nvivo_md_langevin(device float4*v[[buffer(0)]],device const float4*dyn[[buffer(1)]],constant Command&c[[buffer(2)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount||dyn[g].y==0)return;float A=clamp(c.langevinA,0.f,1.f),var=c.boltzmannKJPerMolK*c.targetTemperatureK*dyn[g].y*max(0.f,1.f-A*A),sigma=sqrt(var);v[g].xyz=A*v[g].xyz+sigma*normal4(g,c).xyz;}

[[host_name("nvivo_md_constraint_position")]] kernel void nvivo_md_constraint_position(device const float4*src[[buffer(0)]],device float4*dst[[buffer(1)]],device const float4*dyn[[buffer(2)]],device const Constraint*q[[buffer(3)]],device const uint*o[[buffer(4)]],device const Incidence*inc[[buffer(5)]],device Status&s[[buffer(6)]],constant Command&c[[buffer(7)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount)return;float3 corr=0;float wi=dyn[g].y;for(uint i=o[g];i<o[g+1];++i){Incidence e=inc[i];Constraint x=q[e.termIndex];uint other=e.localIndex==0?x.atoms.y:x.atoms.x;float wj=dyn[other].y,sum=wi+wj;if(sum<=0)continue;float3 d=minimumImage(src[x.atoms.x].xyz-src[x.atoms.y].xyz,c);float r2=dot(d,d);if(!(r2>c.minimumDistanceNM*c.minimumDistanceNM)){fail(s,statusInvalidGeometry,g);continue;}float C=r2-x.distanceNM*x.distanceNM;corr+=(e.localIndex==0?-wi:wi)*C*d/(2.f*sum*r2);}dst[g]=float4(wrapPosition(src[g].xyz+corr,c),0);}
[[host_name("nvivo_md_constraint_velocity")]] kernel void nvivo_md_constraint_velocity(device const float4*p[[buffer(0)]],device const float4*src[[buffer(1)]],device float4*dst[[buffer(2)]],device const float4*dyn[[buffer(3)]],device const Constraint*q[[buffer(4)]],device const uint*o[[buffer(5)]],device const Incidence*inc[[buffer(6)]],device Status&s[[buffer(7)]],constant Command&c[[buffer(8)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount)return;float3 corr=0;float wi=dyn[g].y;for(uint i=o[g];i<o[g+1];++i){Incidence e=inc[i];Constraint x=q[e.termIndex];uint other=e.localIndex==0?x.atoms.y:x.atoms.x;float wj=dyn[other].y,sum=wi+wj;if(sum<=0)continue;float3 d=minimumImage(p[x.atoms.x].xyz-p[x.atoms.y].xyz,c);float r2=dot(d,d);if(!(r2>c.minimumDistanceNM*c.minimumDistanceNM)){fail(s,statusInvalidGeometry,g);continue;}float rel=dot(d,src[x.atoms.x].xyz-src[x.atoms.y].xyz),lambda=rel/(sum*r2);corr+=(e.localIndex==0?-wi:wi)*lambda*d;}dst[g]=float4(src[g].xyz+corr,0);}
[[host_name("nvivo_md_validate_constraints")]] kernel void nvivo_md_validate_constraints(device const float4*p[[buffer(0)]],device const float4*v[[buffer(1)]],device const Constraint*q[[buffer(2)]],device const uint*o[[buffer(3)]],device const Incidence*inc[[buffer(4)]],device Status&s[[buffer(5)]],constant Command&c[[buffer(6)]],uint g[[thread_position_in_grid]]){if(g>=c.particleCount)return;for(uint i=o[g];i<o[g+1];++i){Incidence e=inc[i];if(e.localIndex!=0)continue;Constraint x=q[e.termIndex];float3 d=minimumImage(p[x.atoms.x].xyz-p[x.atoms.y].xyz,c);float length=sqrt(dot(d,d)),pe=fabs(length-x.distanceNM)/max(x.distanceNM,1e-8f),ve=fabs(dot(d,v[x.atoms.x].xyz-v[x.atoms.y].xyz))/max(x.distanceNM,1e-8f);if(!isfinite(pe)||!isfinite(ve)||pe>c.constraintTolerance||ve>c.constraintTolerance/max(c.dtPS,1e-8f))fail(s,statusConstraint,g);}}
[[host_name("nvivo_md_kinetic")]] kernel void nvivo_md_kinetic(device const float4*v[[buffer(0)]],device const float4*dyn[[buffer(1)]],device float*ke[[buffer(2)]],constant Command&c[[buffer(3)]],uint g[[thread_position_in_grid]]){if(g<c.particleCount)ke[g]=.5f*dyn[g].x*dot(v[g].xyz,v[g].xyz);}
[[host_name("nvivo_md_validate")]] kernel void nvivo_md_validate(device const float4*p[[buffer(0)]],device const float4*v[[buffer(1)]],device const float4*fe[[buffer(2)]],device Status&s[[buffer(3)]],constant Command&c[[buffer(4)]],uint g[[thread_position_in_grid]]){if(g<c.particleCount&&(!all(isfinite(p[g]))||!all(isfinite(v[g]))||!all(isfinite(fe[g]))))fail(s,statusNonFinite,g);}
}