import Foundation

public struct VivoMDPackedSystem:Sendable{
    public struct Bond:Sendable{public var atoms:SIMD2<UInt32>;public var parameters:SIMD2<Float>}
    public struct Angle:Sendable{public var atoms:SIMD4<UInt32>;public var parameters:SIMD2<Float>}
    public struct Torsion:Sendable{public var atoms:SIMD4<UInt32>;public var parameters:SIMD4<Float>}
    public struct Constraint:Sendable{public var atoms:SIMD2<UInt32>;public var distanceNM:Float}
    public struct PairException:Sendable{public var atoms:SIMD2<UInt32>;public var scales:SIMD2<Float>;public var overrideC12C6:SIMD2<Float>;public var flags:UInt32}
    public struct Incidence:Sendable{public var termIndex:UInt32;public var localIndex:UInt32}
    /// 48-byte fixed record: site/count, four parents, four weights.
    public struct LinearVirtualSite:Sendable{public var siteAndCount:SIMD2<UInt32>;public var parents:SIMD4<UInt32>;public var weights:SIMD4<Float>}
    public struct VirtualParentIncidence:Sendable{public var siteIndex:UInt32;public var weight:Float}

    public let systemFingerprint:VivoFingerprint;public let particleCount:UInt32;public let typeCount:UInt32
    public let particleDynamics:[SIMD4<Float>];public let particleTypeIndices:[UInt32];public let typePairC12C6:[SIMD2<Float>]
    public let bonds:[Bond];public let angles:[Angle];public let torsions:[Torsion];public let constraints:[Constraint]
    public let pairExceptions:[PairException];public let exceptionOffsets:[UInt32];public let exceptionPartners:[UInt32];public let exceptionIndices:[UInt32]
    public let bondOffsets:[UInt32];public let bondIncidence:[Incidence];public let angleOffsets:[UInt32];public let angleIncidence:[Incidence];public let torsionOffsets:[UInt32];public let torsionIncidence:[Incidence]
    public let virtualSites:[LinearVirtualSite];public let virtualSiteIndexByParticle:[UInt32];public let virtualParentOffsets:[UInt32];public let virtualParentIncidence:[VirtualParentIncidence]
}

public enum VivoMDSystemPacker{
    public static func pack(_ system:VivoClassicalSystem)throws->VivoMDPackedSystem{
        try VivoClassicalSystemValidator.validate(system);guard system.particles.count<=Int(UInt32.max)else{throw VivoArtifactValidationError.invalid("MD particle count exceeds UInt32 execution ABI")}
        let fingerprint=try system.fingerprint(),typeNames=Array(Set(system.particles.map(\.typeIdentifier))).sorted();guard !typeNames.isEmpty,typeNames.count<=Int(UInt32.max)else{throw VivoArtifactValidationError.invalid("MD force-field type table is empty or exceeds UInt32")};let typeIndex=Dictionary(uniqueKeysWithValues:typeNames.enumerated().map{($0.element,UInt32($0.offset))})
        var dynamics:[SIMD4<Float>]=[],particleTypes:[UInt32]=[];for p in system.particles{let mass=try ff(p.massDa,"particle mass"),inv:Float=p.massDa>0 ? try ff(1/p.massDa,"inverse particle mass"):0,charge=try ff(p.chargeE,"particle charge");guard let type=typeIndex[p.typeIdentifier]else{throw VivoArtifactValidationError.invalid("internal MD type-index construction failure")};dynamics.append(.init(mass,inv,charge,0));particleTypes.append(type)}
        let pairMatrix=try compilePairMatrix(system:system,typeNames:typeNames)
        let bonds=try system.bonds.map{Bond(atoms:.init($0.a,$0.b),parameters:.init(try ff($0.lengthNM,"bond length"),try ff($0.forceConstant,"bond force constant")))}
        let angles=try system.angles.map{Angle(atoms:.init($0.a,$0.b,$0.c,0),parameters:.init(try ff($0.angleRadians,"angle"),try ff($0.forceConstant,"angle force constant")))}
        let torsions=try system.torsions.map{Torsion(atoms:.init($0.a,$0.b,$0.c,$0.d),parameters:.init(Float($0.periodicity),try ff($0.phaseRadians,"torsion phase"),try ff($0.barrierKJPerMol,"torsion barrier"),$0.improper ? 1:0))}
        let constraints=try system.constraints.map{Constraint(atoms:.init($0.a,$0.b),distanceNM:try ff($0.distanceNM,"constraint distance"))}
        let exceptions=try system.nonbondedExceptions.map{v->PairException in var ov=SIMD2<Float>.zero,flags:UInt32=0;if v.sigmaOverrideNM != nil || v.epsilonOverrideKJPerMol != nil{guard let s=v.sigmaOverrideNM,let e=v.epsilonOverrideKJPerMol else{throw VivoArtifactValidationError.invalid("nonbonded exception must provide both sigma and epsilon overrides")};ov=try lj(s,e);flags=1};return .init(atoms:.init(v.a,v.b),scales:.init(try ff(v.coulombScale,"exception Coulomb scale"),try ff(v.lennardJonesScale,"exception LJ scale")),overrideC12C6:ov,flags:flags)}.sorted{pairKey($0.atoms.x,$0.atoms.y)<pairKey($1.atoms.x,$1.atoms.y)}
        let exAdj=try pairAdjacency(exceptions,particleCount:system.particles.count)
        let bAdj=try incidence(termCount:bonds.count,particleCount:system.particles.count){let a=bonds[$0].atoms;return[(a.x,0),(a.y,1)]}
        let aAdj=try incidence(termCount:angles.count,particleCount:system.particles.count){let a=angles[$0].atoms;return[(a.x,0),(a.y,1),(a.z,2)]}
        let tAdj=try incidence(termCount:torsions.count,particleCount:system.particles.count){let a=torsions[$0].atoms;return[(a.x,0),(a.y,1),(a.z,2),(a.w,3)]}
        let virtual=try packVirtualSites(system.linearVirtualSites ?? [],particleCount:system.particles.count)
        return .init(systemFingerprint:fingerprint,particleCount:UInt32(system.particles.count),typeCount:UInt32(typeNames.count),particleDynamics:dynamics,particleTypeIndices:particleTypes,typePairC12C6:pairMatrix,bonds:bonds,angles:angles,torsions:torsions,constraints:constraints,pairExceptions:exceptions,exceptionOffsets:exAdj.offsets,exceptionPartners:exAdj.partners,exceptionIndices:exAdj.indices,bondOffsets:bAdj.offsets,bondIncidence:bAdj.entries,angleOffsets:aAdj.offsets,angleIncidence:aAdj.entries,torsionOffsets:tAdj.offsets,torsionIncidence:tAdj.entries,virtualSites:virtual.sites,virtualSiteIndexByParticle:virtual.mapping,virtualParentOffsets:virtual.offsets,virtualParentIncidence:virtual.incidence)
    }

    private static func packVirtualSites(_ source:[VivoLinearVirtualSite],particleCount:Int)throws->(sites:[VivoMDPackedSystem.LinearVirtualSite],mapping:[UInt32],offsets:[UInt32],incidence:[VivoMDPackedSystem.VirtualParentIncidence]){
        var sites:[VivoMDPackedSystem.LinearVirtualSite]=[],mapping=[UInt32](repeating:UInt32.max,count:particleCount),buckets=[[VivoMDPackedSystem.VirtualParentIncidence]](repeating:[],count:particleCount)
        for item in source{guard let siteIndex=UInt32(exactly:sites.count)else{throw VivoArtifactValidationError.invalid("virtual-site table exceeds UInt32")};var parents=SIMD4<UInt32>(repeating:0),weights=SIMD4<Float>(repeating:0);for i in item.parentParticles.indices{parents[i]=item.parentParticles[i];weights[i]=try ff(item.weights[i],"virtual-site weight");buckets[Int(item.parentParticles[i])].append(.init(siteIndex:siteIndex,weight:weights[i]))};sites.append(.init(siteAndCount:.init(item.siteParticle,UInt32(item.parentParticles.count)),parents:parents,weights:weights));mapping[Int(item.siteParticle)]=siteIndex}
        var offsets:[UInt32]=[0],incidence:[VivoMDPackedSystem.VirtualParentIncidence]=[];for bucket in buckets{incidence.append(contentsOf:bucket);guard let next=UInt32(exactly:incidence.count)else{throw VivoArtifactValidationError.invalid("virtual parent incidence exceeds UInt32")};offsets.append(next)};return(sites,mapping,offsets,incidence)
    }
    private static func compilePairMatrix(system:VivoClassicalSystem,typeNames:[String])throws->[SIMD2<Float>]{var by:[String:VivoClassicalParticle]=[:];for p in system.particles where by[p.typeIdentifier]==nil{by[p.typeIdentifier]=p};let n=typeNames.count;var out=[SIMD2<Float>](repeating:.zero,count:n*n);if system.mixingRule == .explicitPairTable{guard let pairs=system.nonbondedTypePairs else{throw VivoArtifactValidationError.invalid("explicit pair table disappeared after validation")};var lookup:[String:VivoNonbondedTypePair]=[:];for p in pairs{lookup[typePairKey(p.typeA,p.typeB)]=p};for i in 0..<n{for j in i..<n{guard let p=lookup[typePairKey(typeNames[i],typeNames[j])]else{throw VivoArtifactValidationError.invalid("explicit pair table is incomplete during MD packing")};let v=SIMD2<Float>(try ff(p.c12KJNM12PerMol,"C12"),try ff(p.c6KJNM6PerMol,"C6"));out[i*n+j]=v;out[j*n+i]=v}};return out};for i in 0..<n{guard let l=by[typeNames[i]]else{throw VivoArtifactValidationError.invalid("missing representative type")};for j in i..<n{guard let r=by[typeNames[j]]else{throw VivoArtifactValidationError.invalid("missing representative type")};let sigma:Double,epsilon=sqrt(l.epsilonKJPerMol*r.epsilonKJPerMol);switch system.mixingRule{case .lorentzBerthelot:sigma=0.5*(l.sigmaNM+r.sigmaNM);case .geometric:sigma=sqrt(l.sigmaNM*r.sigmaNM);case .explicitPairTable:preconditionFailure()};let v=try lj(sigma,epsilon);out[i*n+j]=v;out[j*n+i]=v}};return out}
    private static func lj(_ sigma:Double,_ epsilon:Double)throws->SIMD2<Float>{guard sigma.isFinite,sigma>=0,epsilon.isFinite,epsilon>=0 else{throw VivoArtifactValidationError.invalid("LJ sigma/epsilon is invalid")};if sigma==0||epsilon==0{return .zero};let s6=pow(sigma,6),c6=4*epsilon*s6,c12=c6*s6;return .init(try ff(c12,"derived C12"),try ff(c6,"derived C6"))}
    private static func ff(_ value:Double,_ label:String)throws->Float{guard value.isFinite,abs(value)<=Double(Float.greatestFiniteMagnitude)else{throw VivoArtifactValidationError.invalid("\(label) cannot be represented by Wave B FP32")};let f=Float(value);if value != 0,f==0{throw VivoArtifactValidationError.invalid("\(label) underflows Wave B FP32")};return f}
    private static func typePairKey(_ a:String,_ b:String)->String{a<=b ? a+"\u{0}"+b:b+"\u{0}"+a};private static func pairKey(_ a:UInt32,_ b:UInt32)->UInt64{UInt64(min(a,b))<<32|UInt64(max(a,b))}
    private static func incidence(termCount:Int,particleCount:Int,members:(Int)->[(UInt32,UInt32)])throws->(offsets:[UInt32],entries:[VivoMDPackedSystem.Incidence]){var buckets=[[VivoMDPackedSystem.Incidence]](repeating:[],count:particleCount);for t in 0..<termCount{guard let ti=UInt32(exactly:t)else{throw VivoArtifactValidationError.invalid("MD term count exceeds UInt32")};for(p,l)in members(t){guard p<UInt32(particleCount)else{throw VivoArtifactValidationError.invalid("MD incidence references absent particle")};buckets[Int(p)].append(.init(termIndex:ti,localIndex:l))}};var offsets:[UInt32]=[0],entries:[VivoMDPackedSystem.Incidence]=[];for b in buckets{entries.append(contentsOf:b);guard let n=UInt32(exactly:entries.count)else{throw VivoArtifactValidationError.invalid("MD incidence exceeds UInt32")};offsets.append(n)};return(offsets,entries)}
    private static func pairAdjacency(_ values:[VivoMDPackedSystem.PairException],particleCount:Int)throws->(offsets:[UInt32],partners:[UInt32],indices:[UInt32]){var buckets=[[(UInt32,UInt32)]](repeating:[],count:particleCount);for(i,v)in values.enumerated(){guard let ix=UInt32(exactly:i),v.atoms.x<UInt32(particleCount),v.atoms.y<UInt32(particleCount)else{throw VivoArtifactValidationError.invalid("MD exception adjacency exceeds ABI")};buckets[Int(v.atoms.x)].append((v.atoms.y,ix));buckets[Int(v.atoms.y)].append((v.atoms.x,ix))};var o:[UInt32]=[0],p:[UInt32]=[],idx:[UInt32]=[];for var b in buckets{b.sort{$0.0<$1.0};for x in b{p.append(x.0);idx.append(x.1)};guard let n=UInt32(exactly:p.count)else{throw VivoArtifactValidationError.invalid("MD exception adjacency exceeds UInt32")};o.append(n)};return(o,p,idx)}
}
