import Foundation
import Metal
import NumiVivoShaders

public enum VivoMDRuntimeError: Error, Sendable, CustomStringConvertible {
    case unsupported([String]); case metal(String)
    public var description:String{switch self{case .unsupported(let v):return "MD execution is unsupported: "+v.joined(separator:"; ");case .metal(let v):return "MD Metal runtime: \(v)"}}
}

public struct VivoMDStepCertificate:Codable,Sendable,Equatable{
    public let systemFingerprint:VivoFingerprint;public let configurationFingerprint:VivoFingerprint
    public let deviceName:String;public let deviceRegistryID:UInt64;public let stepIndex:UInt64
    public let timeBeforePS:Double;public let timeAfterPS:Double;public let committed:Bool
    public let statusFlags:UInt32;public let firstViolationParticle:UInt32?;public let violationCount:UInt32
}

public actor VivoMDMetalRuntime{
    public nonisolated let system:VivoClassicalSystem;public nonisolated let configuration:VivoMDConfiguration
    public nonisolated let systemFingerprint:VivoFingerprint;public nonisolated let configurationFingerprint:VivoFingerprint
    public nonisolated let deviceName:String;public nonisolated let deviceRegistryID:UInt64
    private let queue:MTLCommandQueue,packed:VivoMDPackedSystem,arena:VivoMDGPUArena
    private let pipelines:[NumiVivoKernel:NumiVivoPipeline];private let periodicCell:VivoPeriodicCell?
    private var acceptedStep:UInt64,acceptedTimePS:Double,inFlight=false

    public static func make(system:VivoClassicalSystem,initialState:VivoClassicalInitialState,configuration:VivoMDConfiguration,
                            initialVelocitiesNMPerPS:[VivoVector3D]?=nil,device requestedDevice:MTLDevice?=nil)async throws->VivoMDMetalRuntime{
        try await makeInternal(system:system,initialState:initialState,configuration:configuration,velocities:initialVelocitiesNMPerPS,startStep:0,startTimePS:initialState.sourceTimePS ?? 0,device:requestedDevice)
    }
    public static func restore(system:VivoClassicalSystem,configuration:VivoMDConfiguration,checkpoint:VivoMDCheckpoint,device requestedDevice:MTLDevice?=nil)async throws->VivoMDMetalRuntime{
        let sf=try system.fingerprint(),cf=try configuration.fingerprint();try checkpoint.validate(particleCount:system.particles.count)
        guard checkpoint.systemFingerprint==sf,checkpoint.configurationFingerprint==cf else{throw VivoArtifactValidationError.incompatible("MD checkpoint system or configuration identity differs from requested runtime")}
        let initial=VivoClassicalInitialState(systemFingerprint:sf,positionsNM:checkpoint.positionsNM,periodicCell:checkpoint.periodicCell,sourceTimePS:checkpoint.timePS)
        return try await makeInternal(system:system,initialState:initial,configuration:configuration,velocities:checkpoint.velocitiesNMPerPS,startStep:checkpoint.acceptedStep,startTimePS:checkpoint.timePS,device:requestedDevice)
    }
    private static func makeInternal(system:VivoClassicalSystem,initialState:VivoClassicalInitialState,configuration:VivoMDConfiguration,velocities:[VivoVector3D]?,startStep:UInt64,startTimePS:Double,device requestedDevice:MTLDevice?)async throws->VivoMDMetalRuntime{
        let report=try VivoMDCapabilityAnalyzer.analyze(system:system,initialState:initialState,configuration:configuration);var blockers=report.blockers
        if configuration.electrostatics == .pme{blockers.append("PME reciprocal-space execution is not installed yet")}
        if configuration.ensemble == .npt || configuration.barostat != .none{blockers.append("NPT barostat execution is not installed yet")}
        if configuration.thermostat == .velocityRescale{blockers.append("stochastic velocity-rescale thermostat is not installed yet")}
        if configuration.ensemble == .nvt,configuration.thermostat != .langevinMiddle{blockers.append("current NVT execution requires langevinMiddle")}
        if configuration.ensemble == .nve,configuration.thermostat != .none{blockers.append("NVE cannot use a thermostat")}
        if let cell=initialState.periodicCell{try VivoMDMetalABI.validateMinimumImageCutoff(configuration.cutoffNM,cell:cell);if configuration.resolvedNeighborListEnabled{try VivoMDMetalABI.validateNeighborRadius(configuration.cutoffNM+configuration.neighborSkinNM,cell:cell)}}
        guard blockers.isEmpty else{throw VivoMDRuntimeError.unsupported(Array(Set(blockers)).sorted())};guard startTimePS.isFinite,startTimePS>=0 else{throw VivoMDRuntimeError.metal("initial MD clock is invalid")}
        let packed=try VivoMDSystemPacker.pack(system),device=try requestedDevice ?? VivoMetalDeviceSelector.productionDevice();guard device.hasUnifiedMemory,let queue=device.makeCommandQueue()else{throw VivoMDRuntimeError.metal("Apple-silicon unified memory and command queue are required")};queue.label="NumiVivo.MD.Queue"
        let catalog=try NumiVivoPipelineCatalog(device:device);let required:[NumiVivoKernel]=[.mdClearForce,.mdClearStatus,.mdBonded,.mdBuildNeighborList,.mdValidateNeighborDisplacement,.mdNonbondedNeighbor,.mdNonbondedDirect,.mdHalfKick,.mdDrift,.mdLangevin,.mdConstraintPosition,.mdConstraintVelocity,.mdValidateConstraints,.mdKinetic,.mdValidate]
        var pipelines:[NumiVivoKernel:NumiVivoPipeline]=[:];for kernel in required{pipelines[kernel]=try await catalog.pipeline(kernel)}
        let initialVelocities=velocities ?? [VivoVector3D](repeating:.zero,count:system.particles.count)
        let arena=try await VivoMDGPUArena.make(device:device,queue:queue,packed:packed,initial:initialState,velocities:initialVelocities,configuration:configuration)
        return try .init(system:system,configuration:configuration,packed:packed,queue:queue,arena:arena,pipelines:pipelines,periodicCell:initialState.periodicCell,device:device,acceptedStep:startStep,acceptedTimePS:startTimePS)
    }
    private init(system:VivoClassicalSystem,configuration:VivoMDConfiguration,packed:VivoMDPackedSystem,queue:MTLCommandQueue,arena:VivoMDGPUArena,pipelines:[NumiVivoKernel:NumiVivoPipeline],periodicCell:VivoPeriodicCell?,device:MTLDevice,acceptedStep:UInt64,acceptedTimePS:Double)throws{
        self.system=system;self.configuration=configuration;self.packed=packed;self.queue=queue;self.arena=arena;self.pipelines=pipelines;self.periodicCell=periodicCell;self.acceptedStep=acceptedStep;self.acceptedTimePS=acceptedTimePS;systemFingerprint=packed.systemFingerprint;configurationFingerprint=try configuration.fingerprint();deviceName=device.name;deviceRegistryID=device.registryID
    }

    public func step()async throws->VivoMDStepCertificate{
        try requireIdle();guard acceptedStep<UInt64.max else{throw VivoMDRuntimeError.metal("MD step index overflow")};inFlight=true;defer{inFlight=false};let before=acceptedTimePS
        let abi=try VivoMDMetalABI.command(packed:packed,configuration:configuration,cell:periodicCell,stepIndex:acceptedStep)
        guard let command=queue.makeCommandBuffer(),let blit=command.makeBlitCommandEncoder()else{throw VivoMDRuntimeError.metal("step command unavailable")};command.label="NumiVivo.MD.step.\(acceptedStep)";let bytes=arena.particleCount*MemoryLayout<SIMD4<Float>>.stride
        blit.copy(from:arena.acceptedPosition,sourceOffset:0,to:arena.candidatePosition,destinationOffset:0,size:bytes);blit.copy(from:arena.acceptedVelocity,sourceOffset:0,to:arena.candidateVelocity,destinationOffset:0,size:bytes);blit.endEncoding();try encodeStatusClear(command)
        if configuration.resolvedNeighborListEnabled{try buildNeighborList(command,position:arena.candidatePosition,abi:abi)}
        try encodeForces(command,position:arena.candidatePosition,abi:abi)
        try encode(.mdHalfKick,command:command,buffers:[arena.candidateVelocity,arena.forceEnergy,arena.dynamics],abi:abi);if !packed.constraints.isEmpty{try encodeVelocityConstraints(command,abi:abi)}
        if configuration.ensemble == .nvt{var half=abi;half.dtPS*=0.5;try encode(.mdDrift,command:command,buffers:[arena.candidatePosition,arena.candidateVelocity,arena.dynamics],abi:half);if !packed.constraints.isEmpty{try encodePositionConstraints(command,abi:abi)};try encode(.mdLangevin,command:command,buffers:[arena.candidateVelocity,arena.dynamics],abi:abi);if !packed.constraints.isEmpty{try encodeVelocityConstraints(command,abi:abi)};try encode(.mdDrift,command:command,buffers:[arena.candidatePosition,arena.candidateVelocity,arena.dynamics],abi:half);if !packed.constraints.isEmpty{try encodePositionConstraints(command,abi:abi)}}else{try encode(.mdDrift,command:command,buffers:[arena.candidatePosition,arena.candidateVelocity,arena.dynamics],abi:abi);if !packed.constraints.isEmpty{try encodePositionConstraints(command,abi:abi)}}
        if configuration.resolvedNeighborListEnabled{try encode(.mdValidateNeighborDisplacement,command:command,buffers:[arena.candidatePosition,arena.neighborReferencePosition,arena.status],abi:abi)}
        try encodeForces(command,position:arena.candidatePosition,abi:abi);try encode(.mdHalfKick,command:command,buffers:[arena.candidateVelocity,arena.forceEnergy,arena.dynamics],abi:abi)
        if !packed.constraints.isEmpty{try encodeVelocityConstraints(command,abi:abi);try encode(.mdValidateConstraints,command:command,buffers:[arena.candidatePosition,arena.candidateVelocity,arena.constraints,arena.constraintOffsets,arena.constraintIncidence,arena.status],abi:abi)}
        try encode(.mdValidate,command:command,buffers:[arena.candidatePosition,arena.candidateVelocity,arena.forceEnergy,arena.status],abi:abi);try await complete(command)
        let status=arena.status.contents().assumingMemoryBound(to:VivoMDMetalStatus.self).pointee,first=status.firstParticle==UInt32.max ? nil:status.firstParticle
        guard status.flags==0 else{return .init(systemFingerprint:systemFingerprint,configurationFingerprint:configurationFingerprint,deviceName:deviceName,deviceRegistryID:deviceRegistryID,stepIndex:acceptedStep,timeBeforePS:before,timeAfterPS:before,committed:false,statusFlags:status.flags,firstViolationParticle:first,violationCount:status.violationCount)}
        arena.commit();acceptedStep+=1;acceptedTimePS+=configuration.timeStepPS;return .init(systemFingerprint:systemFingerprint,configurationFingerprint:configurationFingerprint,deviceName:deviceName,deviceRegistryID:deviceRegistryID,stepIndex:acceptedStep-1,timeBeforePS:before,timeAfterPS:acceptedTimePS,committed:true,statusFlags:0,firstViolationParticle:nil,violationCount:0)
    }

    public func snapshot()async throws->VivoMDStateSnapshot{try requireIdle();let v=try await readAcceptedState();let r=VivoMDStateSnapshot(systemFingerprint:systemFingerprint,configurationFingerprint:configurationFingerprint,stepIndex:acceptedStep,timePS:acceptedTimePS,positionsNM:v.positions,velocitiesNMPerPS:v.velocities,periodicCell:periodicCell);try r.validate(particleCount:arena.particleCount);return r}
    public func checkpoint()async throws->VivoMDCheckpoint{let s=try await snapshot();let v=VivoMDCheckpoint(systemFingerprint:systemFingerprint,configurationFingerprint:configurationFingerprint,acceptedStep:acceptedStep,timePS:acceptedTimePS,positionsNM:s.positionsNM,velocitiesNMPerPS:s.velocitiesNMPerPS,periodicCell:periodicCell);try v.validate(particleCount:arena.particleCount);return v}
    public func observables()async throws->VivoMDObservables{
        try requireIdle();inFlight=true;defer{inFlight=false};let abi=try VivoMDMetalABI.command(packed:packed,configuration:configuration,cell:periodicCell,stepIndex:acceptedStep);guard let command=queue.makeCommandBuffer()else{throw VivoMDRuntimeError.metal("observables command unavailable")};try encodeStatusClear(command)
        if configuration.resolvedNeighborListEnabled{try buildNeighborList(command,position:arena.acceptedPosition,abi:abi)};try encodeForces(command,position:arena.acceptedPosition,abi:abi);try encode(.mdKinetic,command:command,buffers:[arena.acceptedVelocity,arena.dynamics,arena.kinetic],abi:abi)
        guard let blit=command.makeBlitCommandEncoder()else{throw VivoMDRuntimeError.metal("observables readback encoder unavailable")};let vb=arena.particleCount*MemoryLayout<SIMD4<Float>>.stride,sb=arena.particleCount*4;blit.copy(from:arena.forceEnergy,sourceOffset:0,to:arena.forceEnergyReadback,destinationOffset:0,size:vb);blit.copy(from:arena.kinetic,sourceOffset:0,to:arena.kineticReadback,destinationOffset:0,size:sb);blit.endEncoding();try await complete(command)
        let st=arena.status.contents().assumingMemoryBound(to:VivoMDMetalStatus.self).pointee;guard st.flags==0 else{throw VivoMDRuntimeError.metal("accepted-state force evaluation failed with status \(st.flags)")};let e=arena.forceEnergyReadback.contents().assumingMemoryBound(to:SIMD4<Float>.self),k=arena.kineticReadback.contents().assumingMemoryBound(to:Float.self);var pe=0.0,ke=0.0;for i in 0..<arena.particleCount{pe+=Double(e[i].w);ke+=Double(k[i])};let massive=UInt64(system.particles.lazy.filter{$0.massDa>0}.count),m=massive.multipliedReportingOverflow(by:3);guard !m.overflow else{throw VivoMDRuntimeError.metal("degrees-of-freedom count overflow")};let nc=UInt64(system.constraints.count),dof=m.partialValue>nc ? m.partialValue-nc:0,t=dof>0 ? 2*ke/(Double(dof)*0.00831446261815324):nil;guard pe.isFinite,ke.isFinite,t?.isFinite != false else{throw VivoMDRuntimeError.metal("accepted observables are non-finite")};return .init(systemFingerprint:systemFingerprint,configurationFingerprint:configurationFingerprint,stepIndex:acceptedStep,timePS:acceptedTimePS,potentialEnergyKJPerMol:pe,kineticEnergyKJPerMol:ke,temperatureK:t,degreesOfFreedom:dof)
    }

    private func buildNeighborList(_ command:MTLCommandBuffer,position:MTLBuffer,abi:VivoMDMetalCommand)throws{guard abi.neighborCapacity==arena.neighborCapacity else{throw VivoMDRuntimeError.metal("neighbor-list ABI capacity differs from arena allocation")};try encode(.mdBuildNeighborList,command:command,buffers:[position,arena.neighborCounts,arena.neighborIndices,arena.neighborReferencePosition,arena.status],abi:abi)}
    private func encodePositionConstraints(_ command:MTLCommandBuffer,abi:VivoMDMetalCommand)throws{var source=arena.candidatePosition,destination=arena.positionScratch,sourceIsCandidate=true;for _ in 0..<configuration.maximumConstraintIterations{try encode(.mdConstraintPosition,command:command,buffers:[source,destination,arena.dynamics,arena.constraints,arena.constraintOffsets,arena.constraintIncidence,arena.status],abi:abi);swap(&source,&destination);sourceIsCandidate.toggle()};if !sourceIsCandidate{try copy(command,from:source,to:arena.candidatePosition)}}
    private func encodeVelocityConstraints(_ command:MTLCommandBuffer,abi:VivoMDMetalCommand)throws{var source=arena.candidateVelocity,destination=arena.velocityScratch,sourceIsCandidate=true;for _ in 0..<configuration.maximumConstraintIterations{try encode(.mdConstraintVelocity,command:command,buffers:[arena.candidatePosition,source,destination,arena.dynamics,arena.constraints,arena.constraintOffsets,arena.constraintIncidence,arena.status],abi:abi);swap(&source,&destination);sourceIsCandidate.toggle()};if !sourceIsCandidate{try copy(command,from:source,to:arena.candidateVelocity)}}
    private func encodeForces(_ command:MTLCommandBuffer,position:MTLBuffer,abi:VivoMDMetalCommand)throws{try encode(.mdClearForce,command:command,buffers:[arena.forceEnergy],abi:abi);try encode(.mdBonded,command:command,buffers:[position,arena.forceEnergy,arena.bonds,arena.bondOffsets,arena.bondIncidence,arena.angles,arena.angleOffsets,arena.angleIncidence,arena.torsions,arena.torsionOffsets,arena.torsionIncidence,arena.status],abi:abi);if configuration.resolvedNeighborListEnabled{try encode(.mdNonbondedNeighbor,command:command,buffers:[position,arena.forceEnergy,arena.dynamics,arena.typeIndices,arena.pairMatrix,arena.exceptions,arena.exceptionOffsets,arena.exceptionPartners,arena.exceptionIndices,arena.neighborCounts,arena.neighborIndices,arena.status],abi:abi)}else{try encode(.mdNonbondedDirect,command:command,buffers:[position,arena.forceEnergy,arena.dynamics,arena.typeIndices,arena.pairMatrix,arena.exceptions,arena.exceptionOffsets,arena.exceptionPartners,arena.exceptionIndices,arena.status],abi:abi)}}
    private func readAcceptedState()async throws->(positions:[VivoVector3D],velocities:[VivoVector3D]){inFlight=true;defer{inFlight=false};guard let command=queue.makeCommandBuffer(),let blit=command.makeBlitCommandEncoder()else{throw VivoMDRuntimeError.metal("state readback command unavailable")};let bytes=arena.particleCount*MemoryLayout<SIMD4<Float>>.stride;blit.copy(from:arena.acceptedPosition,sourceOffset:0,to:arena.positionReadback,destinationOffset:0,size:bytes);blit.copy(from:arena.acceptedVelocity,sourceOffset:0,to:arena.velocityReadback,destinationOffset:0,size:bytes);blit.endEncoding();try await complete(command);let p=arena.positionReadback.contents().assumingMemoryBound(to:SIMD4<Float>.self),v=arena.velocityReadback.contents().assumingMemoryBound(to:SIMD4<Float>.self);var pp:[VivoVector3D]=[],vv:[VivoVector3D]=[];pp.reserveCapacity(arena.particleCount);vv.reserveCapacity(arena.particleCount);for i in 0..<arena.particleCount{pp.append(.init(Double(p[i].x),Double(p[i].y),Double(p[i].z)));vv.append(.init(Double(v[i].x),Double(v[i].y),Double(v[i].z)))};return(pp,vv)}
    private func encodeStatusClear(_ command:MTLCommandBuffer)throws{guard let p=pipelines[.mdClearStatus],let e=command.makeComputeCommandEncoder()else{throw VivoMDRuntimeError.metal("status-clear encoder unavailable")};e.setComputePipelineState(p.state);e.setBuffer(arena.status,offset:0,index:0);e.dispatchThreads(.init(width:1,height:1,depth:1),threadsPerThreadgroup:.init(width:1,height:1,depth:1));e.endEncoding()}
    private func encode(_ kernel:NumiVivoKernel,command:MTLCommandBuffer,buffers:[MTLBuffer],abi:VivoMDMetalCommand)throws{guard let p=pipelines[kernel],let e=command.makeComputeCommandEncoder()else{throw VivoMDRuntimeError.metal("encoder unavailable for \(kernel.rawValue)")};e.label=kernel.rawValue;e.setComputePipelineState(p.state);for(i,b)in buffers.enumerated(){e.setBuffer(b,offset:0,index:i)};var a=abi;e.setBytes(&a,length:MemoryLayout<VivoMDMetalCommand>.stride,index:buffers.count);e.dispatchThreads(p.gridSize(for:arena.particleCount),threadsPerThreadgroup:p.threadgroupSize(for:arena.particleCount));e.endEncoding()}
    private func copy(_ command:MTLCommandBuffer,from:MTLBuffer,to:MTLBuffer)throws{guard let b=command.makeBlitCommandEncoder()else{throw VivoMDRuntimeError.metal("copy encoder unavailable")};b.copy(from:from,sourceOffset:0,to:to,destinationOffset:0,size:arena.particleCount*MemoryLayout<SIMD4<Float>>.stride);b.endEncoding()}
    private func requireIdle()throws{guard !inFlight else{throw VivoMDRuntimeError.metal("MD operation already in flight")}}
    private func complete(_ command:MTLCommandBuffer)async throws{try await withCheckedThrowingContinuation{(c:CheckedContinuation<Void,Error>)in command.addCompletedHandler{v in if let e=v.error{c.resume(throwing:VivoMDRuntimeError.metal(String(describing:e)))}else{c.resume(returning:())}};command.commit()}}
}
