import Foundation
@preconcurrency import Metal

final class VivoMDGPUArena:@unchecked Sendable{
    let particleCount:Int;let neighborCapacity:UInt32
    let positionA,positionB,velocityA,velocityB,positionScratch,velocityScratch:MTLBuffer
    let forceEnergy,kinetic,status,dynamics,typeIndices,pairMatrix:MTLBuffer
    let bonds,bondOffsets,bondIncidence,angles,angleOffsets,angleIncidence,torsions,torsionOffsets,torsionIncidence:MTLBuffer
    let constraints,constraintOffsets,constraintIncidence,exceptions,exceptionOffsets,exceptionPartners,exceptionIndices:MTLBuffer
    let virtualSites,virtualSiteIndexByParticle,virtualParentOffsets,virtualParentIncidence:MTLBuffer
    let neighborCounts,neighborIndices,neighborReferencePosition:MTLBuffer
    let positionReadback,velocityReadback,forceEnergyReadback,kineticReadback:MTLBuffer
    private(set)var acceptedIsA=true
    var acceptedPosition:MTLBuffer{acceptedIsA ? positionA:positionB};var candidatePosition:MTLBuffer{acceptedIsA ? positionB:positionA};var acceptedVelocity:MTLBuffer{acceptedIsA ? velocityA:velocityB};var candidateVelocity:MTLBuffer{acceptedIsA ? velocityB:velocityA};func commit(){acceptedIsA.toggle()}

    static func make(device:MTLDevice,queue:MTLCommandQueue,packed:VivoMDPackedSystem,initial:VivoClassicalInitialState,velocities:[VivoVector3D],configuration:VivoMDConfiguration)async throws->VivoMDGPUArena{
        try VivoMDMetalABI.validate();let count=Int(packed.particleCount);guard initial.positionsNM.count==count,velocities.count==count else{throw VivoMDRuntimeError.metal("initial position/velocity shape mismatch")};let positions=try initial.positionsNM.map{try vector($0,label:"position")},velocityVectors=try velocities.map{try vector($0,label:"velocity")},constraintAdjacency=try makeConstraintIncidence(packed.constraints,particleCount:count)
        let maximumPossible=max(count-1,1),requested=Int(configuration.resolvedMaximumNeighborsPerParticle),neighborCapacity=UInt32(max(1,min(requested,maximumPossible))),neighborElements=UInt64(count)*UInt64(neighborCapacity);guard neighborElements<=UInt64(Int.max),neighborElements<=UInt64(device.maxBufferLength/4)else{throw VivoMDRuntimeError.metal("Verlet neighbor-list capacity exceeds Metal buffer limits")}
        guard let upload=queue.makeCommandBuffer(),let blit=upload.makeBlitCommandEncoder()else{throw VivoMDRuntimeError.metal("initial upload command unavailable")};var staging:[MTLBuffer]=[]
        func immutable<T>(_ values:[T],_ label:String)throws->MTLBuffer{let length=max(values.count*MemoryLayout<T>.stride,16);guard length<=device.maxBufferLength,let target=device.makeBuffer(length:length,options:.storageModePrivate)else{throw VivoMDRuntimeError.metal("cannot allocate \(label) (\(length) bytes)")};target.label=label;if !values.isEmpty{let stage:MTLBuffer?=values.withUnsafeBufferPointer{s in guard let base=s.baseAddress else{return nil};return device.makeBuffer(bytes:base,length:values.count*MemoryLayout<T>.stride,options:.storageModeShared)};guard let stage else{throw VivoMDRuntimeError.metal("cannot stage \(label)")};staging.append(stage);blit.copy(from:stage,sourceOffset:0,to:target,destinationOffset:0,size:values.count*MemoryLayout<T>.stride)};return target}
        let positionA=try immutable(positions,"NumiVivo.MD.positionA"),positionB=try immutable(positions,"NumiVivo.MD.positionB"),velocityA=try immutable(velocityVectors,"NumiVivo.MD.velocityA"),velocityB=try immutable(velocityVectors,"NumiVivo.MD.velocityB")
        let dynamics=try immutable(packed.particleDynamics,"NumiVivo.MD.dynamics"),typeIndices=try immutable(packed.particleTypeIndices,"NumiVivo.MD.typeIndices"),pairMatrix=try immutable(packed.typePairC12C6,"NumiVivo.MD.pairMatrix")
        let bonds=try immutable(packed.bonds,"NumiVivo.MD.bonds"),bondOffsets=try immutable(packed.bondOffsets,"NumiVivo.MD.bondOffsets"),bondIncidence=try immutable(packed.bondIncidence,"NumiVivo.MD.bondIncidence"),angles=try immutable(packed.angles,"NumiVivo.MD.angles"),angleOffsets=try immutable(packed.angleOffsets,"NumiVivo.MD.angleOffsets"),angleIncidence=try immutable(packed.angleIncidence,"NumiVivo.MD.angleIncidence"),torsions=try immutable(packed.torsions,"NumiVivo.MD.torsions"),torsionOffsets=try immutable(packed.torsionOffsets,"NumiVivo.MD.torsionOffsets"),torsionIncidence=try immutable(packed.torsionIncidence,"NumiVivo.MD.torsionIncidence")
        let constraints=try immutable(packed.constraints,"NumiVivo.MD.constraints"),constraintOffsets=try immutable(constraintAdjacency.offsets,"NumiVivo.MD.constraintOffsets"),constraintIncidence=try immutable(constraintAdjacency.entries,"NumiVivo.MD.constraintIncidence"),exceptions=try immutable(packed.pairExceptions,"NumiVivo.MD.exceptions"),exceptionOffsets=try immutable(packed.exceptionOffsets,"NumiVivo.MD.exceptionOffsets"),exceptionPartners=try immutable(packed.exceptionPartners,"NumiVivo.MD.exceptionPartners"),exceptionIndices=try immutable(packed.exceptionIndices,"NumiVivo.MD.exceptionIndices")
        let virtualSites=try immutable(packed.virtualSites,"NumiVivo.MD.virtualSites"),virtualMap=try immutable(packed.virtualSiteIndexByParticle,"NumiVivo.MD.virtualSiteIndexByParticle"),virtualOffsets=try immutable(packed.virtualParentOffsets,"NumiVivo.MD.virtualParentOffsets"),virtualIncidence=try immutable(packed.virtualParentIncidence,"NumiVivo.MD.virtualParentIncidence")
        blit.endEncoding();try await complete(upload);_=staging
        let vectorBytes=max(count*MemoryLayout<SIMD4<Float>>.stride,16),scalarBytes=max(count*4,16),neighborBytes=max(Int(neighborElements)*4,16)
        func buffer(_ length:Int,_ storage:MTLResourceOptions,_ label:String)throws->MTLBuffer{guard length<=device.maxBufferLength,let v=device.makeBuffer(length:length,options:storage)else{throw VivoMDRuntimeError.metal("cannot allocate \(label)")};v.label=label;return v}
        return try .init(particleCount:count,neighborCapacity:neighborCapacity,positionA:positionA,positionB:positionB,velocityA:velocityA,velocityB:velocityB,positionScratch:buffer(vectorBytes,.storageModePrivate,"NumiVivo.MD.positionScratch"),velocityScratch:buffer(vectorBytes,.storageModePrivate,"NumiVivo.MD.velocityScratch"),forceEnergy:buffer(vectorBytes,.storageModePrivate,"NumiVivo.MD.forceEnergy"),kinetic:buffer(scalarBytes,.storageModePrivate,"NumiVivo.MD.kinetic"),status:buffer(16,.storageModeShared,"NumiVivo.MD.status"),dynamics:dynamics,typeIndices:typeIndices,pairMatrix:pairMatrix,bonds:bonds,bondOffsets:bondOffsets,bondIncidence:bondIncidence,angles:angles,angleOffsets:angleOffsets,angleIncidence:angleIncidence,torsions:torsions,torsionOffsets:torsionOffsets,torsionIncidence:torsionIncidence,constraints:constraints,constraintOffsets:constraintOffsets,constraintIncidence:constraintIncidence,exceptions:exceptions,exceptionOffsets:exceptionOffsets,exceptionPartners:exceptionPartners,exceptionIndices:exceptionIndices,virtualSites:virtualSites,virtualSiteIndexByParticle:virtualMap,virtualParentOffsets:virtualOffsets,virtualParentIncidence:virtualIncidence,neighborCounts:buffer(max(count*4,16),.storageModePrivate,"NumiVivo.MD.neighborCounts"),neighborIndices:buffer(neighborBytes,.storageModePrivate,"NumiVivo.MD.neighborIndices"),neighborReferencePosition:buffer(vectorBytes,.storageModePrivate,"NumiVivo.MD.neighborReferencePosition"),positionReadback:buffer(vectorBytes,.storageModeShared,"NumiVivo.MD.positionReadback"),velocityReadback:buffer(vectorBytes,.storageModeShared,"NumiVivo.MD.velocityReadback"),forceEnergyReadback:buffer(vectorBytes,.storageModeShared,"NumiVivo.MD.forceReadback"),kineticReadback:buffer(scalarBytes,.storageModeShared,"NumiVivo.MD.kineticReadback"))
    }
    private init(particleCount:Int,neighborCapacity:UInt32,positionA:MTLBuffer,positionB:MTLBuffer,velocityA:MTLBuffer,velocityB:MTLBuffer,positionScratch:MTLBuffer,velocityScratch:MTLBuffer,forceEnergy:MTLBuffer,kinetic:MTLBuffer,status:MTLBuffer,dynamics:MTLBuffer,typeIndices:MTLBuffer,pairMatrix:MTLBuffer,bonds:MTLBuffer,bondOffsets:MTLBuffer,bondIncidence:MTLBuffer,angles:MTLBuffer,angleOffsets:MTLBuffer,angleIncidence:MTLBuffer,torsions:MTLBuffer,torsionOffsets:MTLBuffer,torsionIncidence:MTLBuffer,constraints:MTLBuffer,constraintOffsets:MTLBuffer,constraintIncidence:MTLBuffer,exceptions:MTLBuffer,exceptionOffsets:MTLBuffer,exceptionPartners:MTLBuffer,exceptionIndices:MTLBuffer,virtualSites:MTLBuffer,virtualSiteIndexByParticle:MTLBuffer,virtualParentOffsets:MTLBuffer,virtualParentIncidence:MTLBuffer,neighborCounts:MTLBuffer,neighborIndices:MTLBuffer,neighborReferencePosition:MTLBuffer,positionReadback:MTLBuffer,velocityReadback:MTLBuffer,forceEnergyReadback:MTLBuffer,kineticReadback:MTLBuffer){self.particleCount=particleCount;self.neighborCapacity=neighborCapacity;self.positionA=positionA;self.positionB=positionB;self.velocityA=velocityA;self.velocityB=velocityB;self.positionScratch=positionScratch;self.velocityScratch=velocityScratch;self.forceEnergy=forceEnergy;self.kinetic=kinetic;self.status=status;self.dynamics=dynamics;self.typeIndices=typeIndices;self.pairMatrix=pairMatrix;self.bonds=bonds;self.bondOffsets=bondOffsets;self.bondIncidence=bondIncidence;self.angles=angles;self.angleOffsets=angleOffsets;self.angleIncidence=angleIncidence;self.torsions=torsions;self.torsionOffsets=torsionOffsets;self.torsionIncidence=torsionIncidence;self.constraints=constraints;self.constraintOffsets=constraintOffsets;self.constraintIncidence=constraintIncidence;self.exceptions=exceptions;self.exceptionOffsets=exceptionOffsets;self.exceptionPartners=exceptionPartners;self.exceptionIndices=exceptionIndices;self.virtualSites=virtualSites;self.virtualSiteIndexByParticle=virtualSiteIndexByParticle;self.virtualParentOffsets=virtualParentOffsets;self.virtualParentIncidence=virtualParentIncidence;self.neighborCounts=neighborCounts;self.neighborIndices=neighborIndices;self.neighborReferencePosition=neighborReferencePosition;self.positionReadback=positionReadback;self.velocityReadback=velocityReadback;self.forceEnergyReadback=forceEnergyReadback;self.kineticReadback=kineticReadback}
    private static func makeConstraintIncidence(_ constraints:[VivoMDPackedSystem.Constraint],particleCount:Int)throws->(offsets:[UInt32],entries:[VivoMDPackedSystem.Incidence]){var b=[[VivoMDPackedSystem.Incidence]](repeating:[],count:particleCount);for(i,c)in constraints.enumerated(){guard let t=UInt32(exactly:i),c.atoms.x<UInt32(particleCount),c.atoms.y<UInt32(particleCount)else{throw VivoMDRuntimeError.metal("constraint incidence exceeds execution ABI")};b[Int(c.atoms.x)].append(.init(termIndex:t,localIndex:0));b[Int(c.atoms.y)].append(.init(termIndex:t,localIndex:1))};var o:[UInt32]=[0],e:[VivoMDPackedSystem.Incidence]=[];for x in b{e.append(contentsOf:x);guard let n=UInt32(exactly:e.count)else{throw VivoMDRuntimeError.metal("constraint incidence exceeds UInt32")};o.append(n)};return(o,e)}
    private static func vector(_ v:VivoVector3D,label:String)throws->SIMD4<Float>{guard v.isFinite,abs(v.x)<=Double(Float.greatestFiniteMagnitude),abs(v.y)<=Double(Float.greatestFiniteMagnitude),abs(v.z)<=Double(Float.greatestFiniteMagnitude)else{throw VivoMDRuntimeError.metal("initial \(label) is outside FP32")};return .init(Float(v.x),Float(v.y),Float(v.z),0)}
    private static func complete(_ c:MTLCommandBuffer)async throws{try await withCheckedThrowingContinuation{(x:CheckedContinuation<Void,Error>)in c.addCompletedHandler{v in if let e=v.error{x.resume(throwing:VivoMDRuntimeError.metal(String(describing:e)))}else{x.resume(returning:())}};c.commit()}}
}
