import Foundation

public enum VivoMixingRule:String,Codable,Sendable,CaseIterable{case lorentzBerthelot,geometric,explicitPairTable}
public enum VivoParticleRole:String,Codable,Sendable,CaseIterable{case atom,virtualSite,drude}
public struct VivoClassicalParticle:Codable,Sendable,Equatable{public let index:UInt32;public var atomIndex:UInt32?;public var typeIdentifier:String;public var role:VivoParticleRole;public var massDa:Double;public var chargeE:Double;public var sigmaNM:Double;public var epsilonKJPerMol:Double;public init(index:UInt32,atomIndex:UInt32?,typeIdentifier:String,role:VivoParticleRole = .atom,massDa:Double,chargeE:Double,sigmaNM:Double,epsilonKJPerMol:Double){self.index=index;self.atomIndex=atomIndex;self.typeIdentifier=typeIdentifier;self.role=role;self.massDa=massDa;self.chargeE=chargeE;self.sigmaNM=sigmaNM;self.epsilonKJPerMol=epsilonKJPerMol}}
public struct VivoLinearVirtualSite:Codable,Sendable,Equatable,Hashable{public var siteParticle:UInt32;public var parentParticles:[UInt32];public var weights:[Double];public var provenance:String?;public init(siteParticle:UInt32,parentParticles:[UInt32],weights:[Double],provenance:String?=nil){self.siteParticle=siteParticle;self.parentParticles=parentParticles;self.weights=weights;self.provenance=provenance}}
public struct VivoHarmonicBond:Codable,Sendable,Equatable,Hashable{public var a:UInt32;public var b:UInt32;public var lengthNM:Double;public var forceConstant:Double;public init(a:UInt32,b:UInt32,lengthNM:Double,forceConstant:Double){self.a=a;self.b=b;self.lengthNM=lengthNM;self.forceConstant=forceConstant}}
public struct VivoHarmonicAngle:Codable,Sendable,Equatable,Hashable{public var a:UInt32;public var b:UInt32;public var c:UInt32;public var angleRadians:Double;public var forceConstant:Double;public init(a:UInt32,b:UInt32,c:UInt32,angleRadians:Double,forceConstant:Double){self.a=a;self.b=b;self.c=c;self.angleRadians=angleRadians;self.forceConstant=forceConstant}}
public struct VivoPeriodicTorsion:Codable,Sendable,Equatable,Hashable{public var a:UInt32;public var b:UInt32;public var c:UInt32;public var d:UInt32;public var periodicity:UInt16;public var phaseRadians:Double;public var barrierKJPerMol:Double;public var improper:Bool;public init(a:UInt32,b:UInt32,c:UInt32,d:UInt32,periodicity:UInt16,phaseRadians:Double,barrierKJPerMol:Double,improper:Bool=false){self.a=a;self.b=b;self.c=c;self.d=d;self.periodicity=periodicity;self.phaseRadians=phaseRadians;self.barrierKJPerMol=barrierKJPerMol;self.improper=improper}}
public struct VivoDistanceConstraint:Codable,Sendable,Equatable,Hashable{public var a:UInt32;public var b:UInt32;public var distanceNM:Double;public init(a:UInt32,b:UInt32,distanceNM:Double){self.a=a;self.b=b;self.distanceNM=distanceNM}}
public struct VivoNonbondedTypePair:Codable,Sendable,Equatable,Hashable{public var typeA:String;public var typeB:String;public var c12KJNM12PerMol:Double;public var c6KJNM6PerMol:Double;public init(typeA:String,typeB:String,c12KJNM12PerMol:Double,c6KJNM6PerMol:Double){self.typeA=typeA;self.typeB=typeB;self.c12KJNM12PerMol=c12KJNM12PerMol;self.c6KJNM6PerMol=c6KJNM6PerMol}}
public struct VivoNonbondedException:Codable,Sendable,Equatable,Hashable{public var a:UInt32;public var b:UInt32;public var coulombScale:Double;public var lennardJonesScale:Double;public var sigmaOverrideNM:Double?;public var epsilonOverrideKJPerMol:Double?;public init(a:UInt32,b:UInt32,coulombScale:Double,lennardJonesScale:Double,sigmaOverrideNM:Double?=nil,epsilonOverrideKJPerMol:Double?=nil){self.a=a;self.b=b;self.coulombScale=coulombScale;self.lennardJonesScale=lennardJonesScale;self.sigmaOverrideNM=sigmaOverrideNM;self.epsilonOverrideKJPerMol=epsilonOverrideKJPerMol}}

public struct VivoClassicalSystem:Codable,Sendable,Equatable{
    public static let schema="numivivo.org/classical-system/v1"
    public var schema:String;public var identifier:String;public var structureFingerprint:VivoFingerprint;public var parameterSourceFingerprints:[VivoFingerprint];public var mixingRule:VivoMixingRule;public var particles:[VivoClassicalParticle];public var bonds:[VivoHarmonicBond];public var angles:[VivoHarmonicAngle];public var torsions:[VivoPeriodicTorsion];public var constraints:[VivoDistanceConstraint]
    /// Optional for backward-compatible v1 decoding. Missing rules keep a valid
    /// archival/import artifact but make the system non-executable by MD.
    public var linearVirtualSites:[VivoLinearVirtualSite]?
    public var nonbondedTypePairs:[VivoNonbondedTypePair]?;public var nonbondedExceptions:[VivoNonbondedException];public var metadata:[String:String]
    public init(identifier:String,structureFingerprint:VivoFingerprint,parameterSourceFingerprints:[VivoFingerprint]=[],mixingRule:VivoMixingRule = .lorentzBerthelot,particles:[VivoClassicalParticle],bonds:[VivoHarmonicBond]=[],angles:[VivoHarmonicAngle]=[],torsions:[VivoPeriodicTorsion]=[],constraints:[VivoDistanceConstraint]=[],linearVirtualSites:[VivoLinearVirtualSite]?=nil,nonbondedTypePairs:[VivoNonbondedTypePair]?=nil,nonbondedExceptions:[VivoNonbondedException]=[],metadata:[String:String]=[:]){schema=Self.schema;self.identifier=identifier;self.structureFingerprint=structureFingerprint;self.parameterSourceFingerprints=parameterSourceFingerprints;self.mixingRule=mixingRule;self.particles=particles;self.bonds=bonds;self.angles=angles;self.torsions=torsions;self.constraints=constraints;self.linearVirtualSites=linearVirtualSites;self.nonbondedTypePairs=nonbondedTypePairs;self.nonbondedExceptions=nonbondedExceptions;self.metadata=metadata}
    public func fingerprint()throws->VivoFingerprint{try VivoClassicalSystemValidator.validate(self);return try VivoCanonicalJSON.fingerprint(VivoCanonicalJSON.encode(self))}
}

public enum VivoClassicalSystemValidator{
    public static func validate(_ s:VivoClassicalSystem,atomCount:UInt32?=nil)throws{
        guard s.schema==VivoClassicalSystem.schema,!s.identifier.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty,!s.particles.isEmpty,s.particles.count<=Int(UInt32.max)else{throw VivoArtifactValidationError.invalid("classical system schema, identifier or particle count is invalid")}
        var types=Set<String>();for(i,p)in s.particles.enumerated(){guard p.index==UInt32(i),!p.typeIdentifier.isEmpty,p.massDa.isFinite,p.massDa>=0,p.chargeE.isFinite,p.sigmaNM.isFinite,p.sigmaNM>=0,p.epsilonKJPerMol.isFinite,p.epsilonKJPerMol>=0 else{throw VivoArtifactValidationError.invalid("classical particle \(i) has invalid index or parameters")};types.insert(p.typeIdentifier);if p.role == .atom,p.massDa<=0{throw VivoArtifactValidationError.invalid("ordinary atom particle \(i) requires positive mass")};if p.role == .virtualSite,p.massDa != 0{throw VivoArtifactValidationError.invalid("virtual-site particle \(i) must be massless")};if let a=p.atomIndex,let atomCount,a>=atomCount{throw VivoArtifactValidationError.invalid("classical particle \(i) references absent structure atom \(a)")}}
        let count=UInt32(s.particles.count),virtualParticles=Set(s.particles.filter{$0.role == .virtualSite}.map(\.index)),sites=s.linearVirtualSites ?? [];var defined=Set<UInt32>()
        for site in sites{guard virtualParticles.contains(site.siteParticle),defined.insert(site.siteParticle).inserted,(2...4).contains(site.parentParticles.count),site.parentParticles.count==site.weights.count,Set(site.parentParticles).count==site.parentParticles.count,site.parentParticles.allSatisfy({$0<count && $0 != site.siteParticle}),site.weights.allSatisfy(\.isFinite)else{throw VivoArtifactValidationError.invalid("linear virtual-site definition is malformed or duplicated")};guard site.parentParticles.allSatisfy({s.particles[Int($0)].role == .atom})else{throw VivoArtifactValidationError.invalid("Wave B linear virtual sites require physical atom parents")};let sum=site.weights.reduce(0,+);guard sum.isFinite,abs(sum-1)<1e-9 else{throw VivoArtifactValidationError.invalid("linear virtual-site weights must sum to one")}}
        guard defined.isSubset(of:virtualParticles) else{throw VivoArtifactValidationError.invalid("virtual-site definition references a non-virtual particle")}
        func pair(_ a:UInt32,_ b:UInt32,_ label:String)throws{guard a != b,a<count,b<count else{throw VivoArtifactValidationError.invalid("\(label) particle pair is invalid")}}
        var bondPairs=Set<UInt64>();func key(_ a:UInt32,_ b:UInt32)->UInt64{UInt64(min(a,b))<<32|UInt64(max(a,b))}
        for b in s.bonds{try pair(b.a,b.b,"bond");guard b.lengthNM.isFinite,b.lengthNM>0,b.forceConstant.isFinite,b.forceConstant>=0,bondPairs.insert(key(b.a,b.b)).inserted else{throw VivoArtifactValidationError.invalid("classical bond is invalid or duplicated")}}
        var angleKeys=Set<String>();for a in s.angles{guard Set([a.a,a.b,a.c]).count==3,[a.a,a.b,a.c].allSatisfy({$0<count}),a.angleRadians.isFinite,a.angleRadians>0,a.angleRadians<Double.pi,a.forceConstant.isFinite,a.forceConstant>=0 else{throw VivoArtifactValidationError.invalid("classical angle is invalid")};let f="\(a.a):\(a.b):\(a.c)",r="\(a.c):\(a.b):\(a.a)";guard angleKeys.insert(min(f,r)).inserted else{throw VivoArtifactValidationError.invalid("duplicate classical angle")}}
        for t in s.torsions{guard Set([t.a,t.b,t.c,t.d]).count==4,[t.a,t.b,t.c,t.d].allSatisfy({$0<count}),t.periodicity>0,t.phaseRadians.isFinite,t.barrierKJPerMol.isFinite else{throw VivoArtifactValidationError.invalid("classical torsion has invalid indices or parameters")}}
        var constraintPairs=Set<UInt64>();for c in s.constraints{try pair(c.a,c.b,"constraint");guard c.distanceNM.isFinite,c.distanceNM>0,constraintPairs.insert(key(c.a,c.b)).inserted else{throw VivoArtifactValidationError.invalid("distance constraint is invalid or duplicated")}}
        if s.mixingRule == .explicitPairTable{guard let pairs=s.nonbondedTypePairs,!pairs.isEmpty else{throw VivoArtifactValidationError.invalid("explicitPairTable requires nonbonded type-pair coefficients")};var keys=Set<String>();for v in pairs{guard types.contains(v.typeA),types.contains(v.typeB),v.c12KJNM12PerMol.isFinite,v.c12KJNM12PerMol>=0,v.c6KJNM6PerMol.isFinite,v.c6KJNM6PerMol>=0 else{throw VivoArtifactValidationError.invalid("nonbonded type-pair coefficient is invalid or references an unused type")};let k=v.typeA<=v.typeB ? "\(v.typeA)\u{0}\(v.typeB)":"\(v.typeB)\u{0}\(v.typeA)";guard keys.insert(k).inserted else{throw VivoArtifactValidationError.invalid("duplicate nonbonded type-pair coefficient")}};let required=types.count*(types.count+1)/2;guard pairs.count==required else{throw VivoArtifactValidationError.invalid("explicit nonbonded table is incomplete: expected \(required) type pairs, found \(pairs.count)")}}else if let p=s.nonbondedTypePairs,!p.isEmpty{throw VivoArtifactValidationError.invalid("nonbonded type-pair coefficients require explicitPairTable mixing rule")}
        var exPairs=Set<UInt64>();for e in s.nonbondedExceptions{try pair(e.a,e.b,"nonbonded exception");guard e.coulombScale.isFinite,e.coulombScale>=0,e.lennardJonesScale.isFinite,e.lennardJonesScale>=0,exPairs.insert(key(e.a,e.b)).inserted else{throw VivoArtifactValidationError.invalid("nonbonded exception is invalid or duplicated")};if let v=e.sigmaOverrideNM,!v.isFinite||v<0{throw VivoArtifactValidationError.invalid("nonbonded sigma override is invalid")};if let v=e.epsilonOverrideKJPerMol,!v.isFinite||v<0{throw VivoArtifactValidationError.invalid("nonbonded epsilon override is invalid")}}
    }
}
